CREATE TABLE IF NOT EXISTS ACCOUNT (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	LABEL TEXT NOT NULL
); 

CREATE TABLE IF NOT EXISTS "TRANSACTION" (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	DATE DATE NOT NULL,
	AMOUNT REAL NOT NULL,
	LABEL TEXT NOT NULL DEFAULT 'Unkown transaction',
	ACCOUNT_ID INTEGER NOT NULL,
	SUB_CATEGORY_ID INTEGER
); 

CREATE TABLE IF NOT EXISTS CATEGORY (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	LABEL TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS SUB_CATEGORY (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	LABEL TEXT NOT NULL,
	CATEGORY_ID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS RULE (
	ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	PRIORITY INTEGER NOT NULL,
	OPERATOR TEXT NOT NULL,
	VALIDATORS TEXT NOT NULL,
	SUB_CATEGORY_ID INTEGER NOT NULL
);